/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sina.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.sina.domain.*;
import com.sina.service.inter.ContentServiceInter;
import com.sina.service.inter.TypeServiceInter;
import com.sina.struts.form.ContentForm;
import com.sina.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-16-2011
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class ContentAction extends DispatchAction {
	
	
	private ContentServiceInter contentService;
	private TypeServiceInter typeService;
	
	
	public void setContentService(ContentServiceInter contentService) {
		this.contentService = contentService;
	}


	public void setTypeService(TypeServiceInter typeService) {
		this.typeService = typeService;
	}


	public ActionForward addContent(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		//获取表单信息
		ContentForm cf=(ContentForm)form;
		//创建一个Content domain对象
		Content content=new Content();
		content.setContent(cf.getContent());
		UserForm uf=(UserForm) request.getSession().getAttribute("userForm");
		content.setName(uf.getName());
		content.setSex(uf.getSex());
		System.out.println("type=="+cf.getType());
		content.setType((Type)typeService.findById(Type.class, Integer.parseInt(cf.getType())));
		
		try {
			contentService.add(content);
		} catch (Exception e) {
			return mapping.findForward("err");
			// TODO: handle exception
		}
		
		//查询出所有的评论
		request.setAttribute("contentsList",contentService.showContents() )  ;
		return mapping.findForward("goShowContent");
		
		
		
	}
}