/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sina.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.sina.domain.Message;
import com.sina.domain.Users;
import com.sina.service.imp.MessageServiceImp;
import com.sina.service.inter.MessageServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 05-30-2011
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class GoMessageUiAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//去获取应该显示的留言信息，完成显示
		//取出该用户收到的信息
		MessageServiceInter messageServiceInter=new MessageServiceImp();
		//取出当前用户
		Users loginUser=(Users) request.getSession().getAttribute("userinfo");
		List<Message> list=messageServiceInter.showMessage(loginUser);
		
		//现在应当list集合放到 session request, application? request
		request.setAttribute("messageList", list);
		
		return mapping.findForward("goMessageUi");
	}
}