/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sina.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.sina.service.inter.TypeServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 06-16-2011
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class LoginAction extends DispatchAction {
	
	private TypeServiceInter typeService;
	
	public void setTypeService(TypeServiceInter typeService) {
		this.typeService = typeService;
	}

	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//这里我们就是把登录用户的姓名和性别保存了session中.
		
		//把所有评论种类获取
		request.setAttribute("list",typeService.showType());
		
		return mapping.findForward("goPublish");
	}
}