@startuml

start
:检查是否可通缉;
:扣除道具;
:在自己身上新增通缉目标记录;

if (给gamesrv发消息) then (true)
:（RPC逻辑）在目标身上修改正在被通缉记录;
endif
:自己通缉令数据入库;
:调用EventNotify，通知通缉事件发生
:usersrv
:消息中心;

stop

@enduml

start
:检查是否可通缉;
:扣除道具;
:在自己身上新增通缉目标记录;

:给gamesrv发消息;
if (在目标身上修改正在被通缉记录) then(true)
:自己通缉令数据入库;
:调用EventNotify，通知通缉事件发生
:usersrv
:消息中心;
else
:可能是两个用户同一时刻通缉另一个用户，都可通缉
但只有一个通缉令能生效
记录一条日志（扣除了通缉令，但未能通缉）;
endif

stop