# jaeger all-in-one
version: '3.2'
services:
  db:
    image: jaegertracing/all-in-one
    container_name: jaeger-all-in-one
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
