version: '3.2'
services:
  # jaeger-collector 收集器
  jaeger-collector:
    image: jaegertracing/jaeger-collector
    container_name: jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://jaeger-es:9200
      - ES_USERNAME=elastic
      - LOG_LEVEL=debug
    ports:
      - 9411:9411
      - 14250:14250
      - 14268:14268
      - 14269:14269
  # jaeger-query UI
  jaeger-query:
    image: jaegertracing/jaeger-query
    container_name: jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://jaeger-es:9200
      - ES_USERNAME=elastic
      - LOG_LEVEL=debug
    ports:
      - 16686:16686
      - 16687:16687

networks:
  default:
    external:
      name: jaeger