version: '2'

services:
    jaeger:
      image: jaegertracing/all-in-one:latest
      ports:
        - '16686:16686'

    tracegen:
      image: jaegertracing/jaeger-tracegen:latest
      environment:
        - JAEGER_AGENT_HOST=jaeger
        - JAEGER_AGENT_PORT=6831
      command: ["-duration", "10s", "-workers", "3", "-pause", "250ms"]
      depends_on:
        - jaeger
