close_inactive: 1m
clean_inactive: 72h
scan_frequency: 10s
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
filebeat.inputs:
  # user
  - type: log
    enabled: true
    scan_frequency: 5s
    exclude_lines: [ '(?i).*DEBUG*.' ]
    include_lines: [ '(?i).*INFO*.', '(?i).*WARN*.' ]
    fields:
      service: elk-user
      # 将info 和 error 区分开
      level: info
      # 在环境变量中增加该值 或者写死在配置文件中
      #ip: ${SERVER_IP}
      clientip: 192.168.1.244
    paths:
      # 这里是容器内的目录 需要在启动时将外部目录挂载到容器里才行
      - /var/logs/api/info_*.log
  - type: log
    enabled: true
    include_lines: [ '(?i).*ERROR*.' ]
    tags: [ "json" ]
    fields:
      service: elk-user
      level: error
      clientip: 192.168.1.244
    paths:
      - /var/logs/api/error_*.log
# 发送到 logstash
output.logstash:
  hosts: [ "elk-logstash:5044" ]

