version: '3.2'
services:
  logstash:
    image: logstash:7.8.0
    container_name: elk-logstash
    restart: always
    volumes:
      # 指定管道配置文件
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:rw
    environment:
      - elasticsearch.hosts=http://elk-es:9200
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    ports:
      - 5044:5044

networks:
  default:
    external:
      name: elk
